<?php

namespace AppBundle\Repository;

/**
 * PersonnageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonnageRepository extends \Doctrine\ORM\EntityRepository
{
}
